//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamiliasraisersEdgeEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string Project { get; set; }
        public int MemberId { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public string RecordStatus { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> ExpirationDateTime { get; set; }
        public Nullable<int> LastFamilyId { get; set; }
        public string FirstNames { get; set; }
        public string LastNames { get; set; }
        public string PreferredName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Gender { get; set; }
        public string AffiliationType { get; set; }
        public string AffiliationStatus { get; set; }
        public Nullable<System.DateTime> AffiliationStatusDate { get; set; }
        public string LiveDead { get; set; }
        public Nullable<System.DateTime> DeathDate { get; set; }
        public Nullable<int> BiologicalMotherMemberId { get; set; }
        public Nullable<int> BiologicalFatherMemberId { get; set; }
        public string OtherAffiliation { get; set; }
        public string OfficialId { get; set; }
        public bool HasFaithOfAgeOrOfficialId { get; set; }
        public string CellularPhoneNumber { get; set; }
        public string Literacy { get; set; }
        public string LastGradePassed { get; set; }
        public Nullable<bool> HasHealthCard { get; set; }
        public string ExceptionInAgePolicy { get; set; }
        public Nullable<int> LastGradePassedYear { get; set; }
        public string LastGradePassedStatus { get; set; }
    
        public virtual CdGender CdGender { get; set; }
    }
}
