//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamiliasraisersEdgeEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiscMemberSponsorInfo
    {
        public string Project { get; set; }
        public int MemberId { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public string RecordStatus { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> ExpirationDateTime { get; set; }
        public string Photo { get; set; }
        public Nullable<System.DateTime> PhotoDate { get; set; }
        public Nullable<System.DateTime> RetakePhotoDate { get; set; }
        public string RetakePhotoUserId { get; set; }
        public Nullable<System.DateTime> LastCarnetPrintDate { get; set; }
        public string SponsorshipLevel { get; set; }
        public string SponsorshipType { get; set; }
        public string Restriction { get; set; }
        public Nullable<System.DateTime> RestrictionDate { get; set; }
        public Nullable<System.DateTime> ExceptionPhotoDate { get; set; }
    
        public virtual CdSponsorMemberRelationType CdSponsorMemberRelationType { get; set; }
        public virtual CdSponsorshipLevel CdSponsorshipLevel { get; set; }
        public virtual CdSponsorshipRestriction CdSponsorshipRestriction { get; set; }
    }
}
