//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamiliasraisersEdgeEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        public int SponsorId { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public string RecordStatus { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> ExpirationDateTime { get; set; }
        public string SponsorNames { get; set; }
        public string Gender { get; set; }
        public string OrganizationContactNames { get; set; }
        public string StateOrProvince { get; set; }
        public string Country { get; set; }
        public Nullable<bool> SpeaksSpanish { get; set; }
    
        public virtual CdCountry CdCountry { get; set; }
        public virtual CdGender CdGender { get; set; }
        public virtual CdStateOrProvince CdStateOrProvince { get; set; }
    }
}
