//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamiliasraisersEdgeEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SponsorMemberRelation
    {
        public string Project { get; set; }
        public int SponsorId { get; set; }
        public int MemberId { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public string RecordStatus { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> ExpirationDateTime { get; set; }
        public string Type { get; set; }
        public string Notes { get; set; }
        public string InactiveReason { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual CdSponsorMemberRelationInactiveReason CdSponsorMemberRelationInactiveReason { get; set; }
        public virtual CdSponsorMemberRelationType CdSponsorMemberRelationType { get; set; }
    }
}
