//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamiliasraisersEdgeEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_AMBF_CondicionesVivienda
    {
        public string Sitio { get; set; }
        public int Familia { get; set; }
        public string Clasificación { get; set; }
        public string TS { get; set; }
        public string Pueblo { get; set; }
        public string Tenencia { get; set; }
        public string Tamaño { get; set; }
        public Nullable<int> Cuartos { get; set; }
        public string Paredes { get; set; }
        public string Paredes_Calidad { get; set; }
        public string Paredes_Notas { get; set; }
        public string Techo { get; set; }
        public string Techo_Calidad { get; set; }
        public string Techo_Notas { get; set; }
        public string Piso { get; set; }
        public string Piso_Calidad { get; set; }
        public string Piso_Notas { get; set; }
        public string Cocina { get; set; }
        public string Cocina_Calidad { get; set; }
        public string Cocina_Notas { get; set; }
        public string Agua { get; set; }
        public string Electricidad { get; set; }
        public string Baño { get; set; }
        public string Drenaje { get; set; }
        public string Higiene { get; set; }
        public string CocinaTecho { get; set; }
        public string CocinaTecho_Calidad { get; set; }
        public string CocinaTecho_Notas { get; set; }
        public string pCultivar { get; set; }
        public string Estufa { get; set; }
    }
}
