//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamiliasraisersEdgeEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GEN_FamiliasAfiliadas
    {
        public string Sitio { get; set; }
        public int Familia { get; set; }
        public string Dirección { get; set; }
        public string Area { get; set; }
        public string Pueblo { get; set; }
        public string Región { get; set; }
        public string Madre { get; set; }
        public string Padre { get; set; }
        public string TS { get; set; }
        public Nullable<System.DateTime> UltimaActualización { get; set; }
        public string Clasificacion { get; set; }
        public string FechaClasificación { get; set; }
        public Nullable<int> Apadrinados { get; set; }
        public Nullable<int> Afiliados { get; set; }
        public Nullable<int> DesafiliadosGraduados { get; set; }
        public string FechaAfiliación { get; set; }
        public string Telefonos { get; set; }
        public Nullable<decimal> Ingresos { get; set; }
        public Nullable<decimal> IngresosJefes { get; set; }
        public string Family { get; set; }
    }
}
