//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamiliasraisersEdgeEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GEN_PoblaciónConDerechos
    {
        public string Sitio { get; set; }
        public int Miembro { get; set; }
        public string Apellidos { get; set; }
        public string Nombres { get; set; }
        public string Genero { get; set; }
        public string Nacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public string RelaciónFamiliar { get; set; }
        public int Familia { get; set; }
        public string Clasificación { get; set; }
        public string FechaClasificación { get; set; }
        public string EstadoFamiliar { get; set; }
        public string Etnia { get; set; }
        public string Pueblo { get; set; }
        public string TS { get; set; }
        public string Región { get; set; }
        public string Teléfono { get; set; }
        public string descSitio { get; set; }
        public string TipoMiembro { get; set; }
        public string GradoAcadémico { get; set; }
    }
}
