//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamiliasraisersEdgeEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_GEN_Apadrinados
    {
        public string Project { get; set; }
        public string Sitio { get; set; }
        public string TipoAfil { get; set; }
        public int No_Afiliación { get; set; }
        public string Apellidos { get; set; }
        public string Nombres { get; set; }
        public string Genero { get; set; }
        public string Nacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<int> Año { get; set; }
        public string Grado { get; set; }
        public string Estado_Educ { get; set; }
        public string Fecha_Estado { get; set; }
        public string ExcepcionEstadoEduc { get; set; }
        public string Sección { get; set; }
        public string Maestro { get; set; }
        public string Nivel_Educ { get; set; }
        public string Escuela { get; set; }
        public string Semaforo { get; set; }
        public string Fase { get; set; }
        public string Razón { get; set; }
        public string FechaEstadoFase { get; set; }
        public Nullable<int> Padrinos { get; set; }
        public string NivelApadrinamiento { get; set; }
        public Nullable<int> Familia { get; set; }
        public string TS { get; set; }
        public string Región { get; set; }
        public string Madre { get; set; }
        public string Padre { get; set; }
        public string Dirección { get; set; }
        public string Pueblo { get; set; }
        public string Area { get; set; }
        public string Telefonos { get; set; }
        public string Clasificación { get; set; }
        public string ProximaClasificacion { get; set; }
        public string Carrera { get; set; }
        public string FechaAfiliacion { get; set; }
        public string Restricción { get; set; }
        public string PuebloEscuela { get; set; }
        public Nullable<decimal> Ingresos { get; set; }
        public string SchoolType { get; set; }
    }
}
